import os
os.system('cls')
from termcolor import colored, cprint
for i in range (2) :
    cprint(" "*5, 'black', 'on_red', end='')
    print(' '*3, end='')
    cprint(' '*5, 'black', 'on_red', end ='')
    print(' '*3, end='')
    cprint(' '*5, 'black', 'on_red', end='')
    print(' '*3, end='')
    cprint(' '*5, 'black', 'on_red', end='')
    print(' '*3,end='')
    cprint(' '*14, 'black', 'on_red')
for i in range (1) :
    cprint(" "*5, 'black', 'on_red', end='')
    print(' '*3, end='')
    cprint(' '*5, 'black', 'on_red', end ='')
    print(' '*3, end='')
    cprint(' '*5, 'black', 'on_red')
for i in range (4) :
    cprint(" "*5, 'black', 'on_red', end='')
    print(' '*3, end='')
    cprint(' '*5, 'black', 'on_red', end ='')
    print(' '*3, end='')
    cprint(' '*5, 'black', 'on_red', end='')
    print(' '*3, end='')
    cprint(' '*5, 'white', 'on_dark_grey', end='')
    print(' '*3,end='')
    cprint(' '*5, 'black', 'on_red')
for i in range (3) :
    cprint(" "*5, 'black', 'on_red', end='')
    print(' '*11, end='')
    cprint(' '*5, 'black', 'on_red', end='')
    print(' '*3,end='')
    cprint(' '*5, 'white', 'on_dark_grey', end='')
    print(' '*3,end='')
    cprint(' '*5, 'black', 'on_red')